# Generated by Django 3.0.7 on 2020-06-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
    ]
